[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "https://morning-divine-needle.solana-devnet.quiknode.pro/db4bd156028b7c76e02b032d3ef844e7fe0c3cbf/"
# cluster = "https://bitter-twilight-night.solana-mainnet.quiknode.pro/a3bdc396f3fdb8417dd5308dde0901f6d470ca44/"

# local
# wallet = "/home/benson/.config/solana/id.json"
# prod
wallet = "/home/benson/TWMtQV3hzKLRpDy67QPcEqkFc6r8vAwxx5UvQ3fkjh5.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
admin-unstake = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/admin-unstake.ts"
update-staking-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/update-staking-config.ts"
check-user-state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/check-user-state.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/mpl_token_metadata.so"
