/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * Arguments used to create {@link StakeInfo}
 * @category Accounts
 * @category generated
 */
export type StakeInfoArgs = {
  startTime: beet.bignum
}

const stakeInfoDiscriminator = [66, 62, 68, 70, 108, 179, 183, 235]
/**
 * Holds the data for the {@link StakeInfo} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class StakeInfo implements StakeInfoArgs {
  private constructor(readonly startTime: beet.bignum) {}

  /**
   * Creates a {@link StakeInfo} instance from the provided args.
   */
  static fromArgs(args: StakeInfoArgs) {
    return new StakeInfo(args.startTime)
  }

  /**
   * Deserializes the {@link StakeInfo} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [StakeInfo, number] {
    return StakeInfo.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link StakeInfo} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey
  ): Promise<StakeInfo> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find StakeInfo account at ${address}`)
    }
    return StakeInfo.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Deserializes the {@link StakeInfo} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [StakeInfo, number] {
    return stakeInfoBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link StakeInfo} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return stakeInfoBeet.serialize({
      accountDiscriminator: stakeInfoDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link StakeInfo}
   */
  static get byteSize() {
    return stakeInfoBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link StakeInfo} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      StakeInfo.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link StakeInfo} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === StakeInfo.byteSize
  }

  /**
   * Returns a readable version of {@link StakeInfo} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      startTime: (() => {
        const x = <{ toNumber: () => number }>this.startTime
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const stakeInfoBeet = new beet.BeetStruct<
  StakeInfo,
  StakeInfoArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['startTime', beet.u64],
  ],
  StakeInfo.fromArgs,
  'StakeInfo'
)
