name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: cargo fmt --verbose
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply format and lint changes
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo clippy --fix --verbose
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply lint changes

